name: Nutriwell CD

on:
  push:
    branches:
      - main
      - develop/improvement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/nutriwell-backend
          git pull origin develop/improvement
          git status
          rm -rf node_modules
          nvm use
          npm install --only=prod
          npm run build
          pm2 restart nutriwell-backend