name: Nutriwell CD

on:
  push:
    branches:
      - main
      - develop/improvement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node based on .nvmrc file
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          npm install pm2 -g
          cd ~/nutriwell-backend
          git pull origin develop/improvement
          git status
          rm -rf node_modules
          npm install --only=prod
          npm run build
          pm2 restart nutriwell-backend